# This app runs with a key and URL for Azure OpenAI Service: https://azure.microsoft.com/en-us/products/cognitive-services/openai-service/
# https://azure.microsoft.com/en-us/products/cognitive-services/openai-service/
# Add the following values in two places: 
# 1. Action secrets in this GitHub Repo: Settings > Secrets and Variables > Actions
# 2. Application settings of you destination App Service: Configuration > Application Settings.
# Values: 
# APPLICATION_OPENAI_KEY=<your-openai-api-key>
# APPLICATION_OPENAI_URL=<your-openai-url>Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: Build and deploy JAR app to Azure Web App - 20210223openaibot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: '20210223openaibot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_24E9272CED624BA6AE705476003C32A1 }}
          package: '*.jar'
